apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexvion-web
  namespace: nexvion
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: nexvion-web
  template:
    metadata:
      labels:
        app: nexvion-web
    spec:
      containers:
        - name: web
          image: acrnexvionz034e.azurecr.io/nexvion-web:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi